source 'http://rubygems.org'
gem 'bundler'
gem 'cukesparse'
gem 'poltergeist'
gem 'yard'
gem 'rake'
gem 'rspec', :require => 'spec'
gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'capybara-webkit'
gem 'nokogiri'
gem 'xml-simple'
gem 'ffi'
gem 'require_all'
gem 'pry'
