source 'http://rubygems.org'
gem 'bundler'
gem 'cukesparse'
gem 'poltergeist'
gem 'yard'
gem 'rake'
gem 'rspec', :require => 'spec'
gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver', '2.45.0.dev3'
gem 'capybara-webkit'
gem 'nokogiri'
gem 'xml-simple'
gem 'ffi'
gem 'require_all'
gem 'pry'
gem 'activesupport'
gem 'minitest'
gem 'rails', '4.2.0'
gem 'curb'
gem 'parallel_tests'
gem 'syntax'
gem 'chromedriver-helper'
gem 'headless'