URL: http://all-ei-dev.elasticbeanstalk.com/
METADATA_URL: http://localhost:5000
METADATA_USERNAME: ecommerceapp@clavistechnology.com
METADATA_PASSWORD: rc223svt
CONTROLLER: chrome
BS_USERNAME: david1347
BS_AUTHKEY: ntnBqvSYwxip1XQUnPM7