URL: <%= ENV['URL'] || 'http://all-ei-dev.elasticbeanstalk.com/' %>

METADATA_URL: <%= ENV['METADATA_URL'] || 'http://all-md-dev.elasticbeanstalk.com/' %>
METADATA_USERNAME: <%= ENV['METADATA_USERNAME'] || 'ecommerceapp@clavistechnology.com' %>
METADATA_PASSWORD: <%= ENV['METADATA_PASSWORD'] || 'rc223svt' %>

CONTROLLER: <%= ENV['CONTROLLER'] || 'chrome' %>
BS_USERNAME: <%= ENV['BS_USERNAME'] || 'david1347' %>
BS_AUTHKEY: <%= ENV['BS_AUTHKEY'] || 'ntnBqvSYwxip1XQUnPM7' %>
RECORD_VIDEO?: <%= ENV['RECORD_VIDEO'] == 'true' %>

USERS:
  KCC US:
    username: kcc_us@clavistechnology.com
    password: Testing!700
  GENERAL MILLS US:
    username: general_mills_us@clavistechnology.com
    password: Testing!800
  KCC US TEST:
    username: kcc_us_test2@clavisinsight.com
    password: Testing!700
  KCC US TEST 2:
    username: kcc_us_test2@clavisinsight.com
    password: Testing!700